apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  SERVER_NAME: "ioManager"
  SERVER_PORT: "4356"
  SERVER_TOKEN_SECRET: "mV|GuHok*+as2fg|I0Wy^"  
  API_STORE_TYPE: mongo
  API_STORE_MONGO: mongodb://admin:uUa4nPAxLfWw@server-db-svc:27017/manager?authSource=admin
  API_AUTH_METHOD_BASIC_USERS: "[\"admin:admin\"]"
  API_AUTH_METHOD: basic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: uUa4nPAxLfWw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
data:
  REACT_APP_SERVER_BASE: /server
  PUBLIC_URL: http://localhost/admin-ui/
  REACT_APP_BASE: /admin-ui
  API_AUTH_METHOD_BASIC_USERS: "[\"admin:admin\"]"
  API_AUTH_METHOD: basic